name: Node.js CI

on:
  push: 
    branches: [ master ]


jobs: 
  build_main: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout   
      uses: actions/checkout@v2
      with: 
        persist-credentials: false
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "yarn"
    
    - run: yarn install
    
    - run: yarn run build:es
      env:
        CI: true
   
    - name: Deploy to prod branch
      uses: ushmm/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: PROD # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
